/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplainersRouteImport } from './routes/explainers'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as ExplainersIndexRouteImport } from './routes/explainers.index'
import { Route as ExplainersIdRouteImport } from './routes/explainers.$id'
import { Route as CitySlugIndexRouteImport } from './routes/city.$slug.index'
import { Route as CitySlugAdminRouteImport } from './routes/city.$slug.admin'
import { Route as CitySlugConstraintsRouteImport } from './routes/city.$slug.constraints'
import { Route as CitySlugFundamentalsRouteImport } from './routes/city.$slug.fundamentals'
import { Route as CitySlugIndustriesRouteImport } from './routes/city.$slug.industries'
import { Route as CitySlugLeversRouteImport } from './routes/city.$slug.levers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainersRoute = ExplainersRouteImport.update({
  id: '/explainers',
  path: '/explainers',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainersIndexRoute = ExplainersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExplainersRoute,
} as any)
const ExplainersIdRoute = ExplainersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExplainersRoute,
} as any)
const CitySlugIndexRoute = CitySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitySlugRoute,
} as any)
const CitySlugAdminRoute = CitySlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CitySlugRoute,
} as any)
const CitySlugConstraintsRoute = CitySlugConstraintsRouteImport.update({
  id: '/constraints',
  path: '/constraints',
  getParentRoute: () => CitySlugRoute,
} as any)
const CitySlugFundamentalsRoute = CitySlugFundamentalsRouteImport.update({
  id: '/fundamentals',
  path: '/fundamentals',
  getParentRoute: () => CitySlugRoute,
} as any)
const CitySlugIndustriesRoute = CitySlugIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => CitySlugRoute,
} as any)
const CitySlugLeversRoute = CitySlugLeversRouteImport.update({
  id: '/levers',
  path: '/levers',
  getParentRoute: () => CitySlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explainers': typeof ExplainersRouteWithChildren
  '/city/$slug': typeof CitySlugRouteWithChildren
  '/explainers/$id': typeof ExplainersIdRoute
  '/explainers/': typeof ExplainersIndexRoute
  '/city/$slug/admin': typeof CitySlugAdminRoute
  '/city/$slug/constraints': typeof CitySlugConstraintsRoute
  '/city/$slug/fundamentals': typeof CitySlugFundamentalsRoute
  '/city/$slug/industries': typeof CitySlugIndustriesRoute
  '/city/$slug/levers': typeof CitySlugLeversRoute
  '/city/$slug/': typeof CitySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explainers/$id': typeof ExplainersIdRoute
  '/explainers': typeof ExplainersIndexRoute
  '/city/$slug/admin': typeof CitySlugAdminRoute
  '/city/$slug/constraints': typeof CitySlugConstraintsRoute
  '/city/$slug/fundamentals': typeof CitySlugFundamentalsRoute
  '/city/$slug/industries': typeof CitySlugIndustriesRoute
  '/city/$slug/levers': typeof CitySlugLeversRoute
  '/city/$slug': typeof CitySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explainers': typeof ExplainersRouteWithChildren
  '/city/$slug': typeof CitySlugRouteWithChildren
  '/explainers/$id': typeof ExplainersIdRoute
  '/explainers/': typeof ExplainersIndexRoute
  '/city/$slug/admin': typeof CitySlugAdminRoute
  '/city/$slug/constraints': typeof CitySlugConstraintsRoute
  '/city/$slug/fundamentals': typeof CitySlugFundamentalsRoute
  '/city/$slug/industries': typeof CitySlugIndustriesRoute
  '/city/$slug/levers': typeof CitySlugLeversRoute
  '/city/$slug/': typeof CitySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explainers'
    | '/city/$slug'
    | '/explainers/$id'
    | '/explainers/'
    | '/city/$slug/admin'
    | '/city/$slug/constraints'
    | '/city/$slug/fundamentals'
    | '/city/$slug/industries'
    | '/city/$slug/levers'
    | '/city/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explainers/$id'
    | '/explainers'
    | '/city/$slug/admin'
    | '/city/$slug/constraints'
    | '/city/$slug/fundamentals'
    | '/city/$slug/industries'
    | '/city/$slug/levers'
    | '/city/$slug'
  id:
    | '__root__'
    | '/'
    | '/explainers'
    | '/city/$slug'
    | '/explainers/$id'
    | '/explainers/'
    | '/city/$slug/admin'
    | '/city/$slug/constraints'
    | '/city/$slug/fundamentals'
    | '/city/$slug/industries'
    | '/city/$slug/levers'
    | '/city/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplainersRoute: typeof ExplainersRouteWithChildren
  CitySlugRoute: typeof CitySlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainers': {
      id: '/explainers'
      path: '/explainers'
      fullPath: '/explainers'
      preLoaderRoute: typeof ExplainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainers/': {
      id: '/explainers/'
      path: '/'
      fullPath: '/explainers/'
      preLoaderRoute: typeof ExplainersIndexRouteImport
      parentRoute: typeof ExplainersRoute
    }
    '/explainers/$id': {
      id: '/explainers/$id'
      path: '/$id'
      fullPath: '/explainers/$id'
      preLoaderRoute: typeof ExplainersIdRouteImport
      parentRoute: typeof ExplainersRoute
    }
    '/city/$slug/': {
      id: '/city/$slug/'
      path: '/'
      fullPath: '/city/$slug/'
      preLoaderRoute: typeof CitySlugIndexRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/city/$slug/admin': {
      id: '/city/$slug/admin'
      path: '/admin'
      fullPath: '/city/$slug/admin'
      preLoaderRoute: typeof CitySlugAdminRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/city/$slug/constraints': {
      id: '/city/$slug/constraints'
      path: '/constraints'
      fullPath: '/city/$slug/constraints'
      preLoaderRoute: typeof CitySlugConstraintsRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/city/$slug/fundamentals': {
      id: '/city/$slug/fundamentals'
      path: '/fundamentals'
      fullPath: '/city/$slug/fundamentals'
      preLoaderRoute: typeof CitySlugFundamentalsRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/city/$slug/industries': {
      id: '/city/$slug/industries'
      path: '/industries'
      fullPath: '/city/$slug/industries'
      preLoaderRoute: typeof CitySlugIndustriesRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/city/$slug/levers': {
      id: '/city/$slug/levers'
      path: '/levers'
      fullPath: '/city/$slug/levers'
      preLoaderRoute: typeof CitySlugLeversRouteImport
      parentRoute: typeof CitySlugRoute
    }
  }
}

interface ExplainersRouteChildren {
  ExplainersIdRoute: typeof ExplainersIdRoute
  ExplainersIndexRoute: typeof ExplainersIndexRoute
}

const ExplainersRouteChildren: ExplainersRouteChildren = {
  ExplainersIdRoute: ExplainersIdRoute,
  ExplainersIndexRoute: ExplainersIndexRoute,
}

const ExplainersRouteWithChildren = ExplainersRoute._addFileChildren(
  ExplainersRouteChildren,
)

interface CitySlugRouteChildren {
  CitySlugAdminRoute: typeof CitySlugAdminRoute
  CitySlugConstraintsRoute: typeof CitySlugConstraintsRoute
  CitySlugFundamentalsRoute: typeof CitySlugFundamentalsRoute
  CitySlugIndustriesRoute: typeof CitySlugIndustriesRoute
  CitySlugLeversRoute: typeof CitySlugLeversRoute
  CitySlugIndexRoute: typeof CitySlugIndexRoute
}

const CitySlugRouteChildren: CitySlugRouteChildren = {
  CitySlugAdminRoute: CitySlugAdminRoute,
  CitySlugConstraintsRoute: CitySlugConstraintsRoute,
  CitySlugFundamentalsRoute: CitySlugFundamentalsRoute,
  CitySlugIndustriesRoute: CitySlugIndustriesRoute,
  CitySlugLeversRoute: CitySlugLeversRoute,
  CitySlugIndexRoute: CitySlugIndexRoute,
}

const CitySlugRouteWithChildren = CitySlugRoute._addFileChildren(
  CitySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplainersRoute: ExplainersRouteWithChildren,
  CitySlugRoute: CitySlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
