#!/usr/bin/env node
/* Port the cities-v-5 prototype (the static site on main) into this app.

   usage:  node scripts/v3/port.mjs --src <directory holding cities-v-5's files>

   e.g.    rm -rf $TMP/v5 && mkdir -p $TMP/v5 && git archive origin/main cities-v-5 | tar -x -C $TMP/v5
           node scripts/v3/port.mjs --src $TMP/v5/cities-v-5

   The source is the folder main's work happens in. That was cities-v-3/
   until 2026-09-14, then cities-v-1/ (an exact copy of v-3), and since
   2026-10-01 cities-v-5/ (a copy of v-1 taken on 2026-09-21, where the
   first three sections have been rewritten since); the "v3" in this
   script's path and in the generated file names dates from the first and
   was kept so nothing had to be rewired.

   Main's page IS the app's shell: its landing, masthead, section tabs and
   pager, journey window, dialogs and every section but Constraints Diagnosis
   come across as they are. React renders only Constraints Diagnosis (and the
   Explainers content) into slots inside that markup. What it writes:

     src/legacy/html/body.html             main's <body>, with the slots and a few swaps (below)
     src/legacy/v3.css                     main's stylesheet, verbatim but for the landing image
     src/legacy/treemap.js                 treemap.js as a module: a function that returns its init()
     src/legacy/xch_geo.js                 the boundary data, verbatim
     src/legacy/industries-2024.js, -2014.js   the metro's industry rows, verbatim
     src/legacy/v3-page.js                 the two inline scripts, wrapped as one module and patched
     src/legacy/assets/landing-page.webp   the landing image (bundled through an import)
     public/legacy/assets/gl_logo.png      the logo the markup references
     public/legacy/rca-distributions.html  the page the Extras section frames, verbatim

   Every edit to main's text is a step in this file, anchored on a line of the
   upstream text and asserted to match exactly once — so a re-sync that no
   longer fits fails loudly here rather than quietly in the browser. */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const args = process.argv.slice(2);
const srcIdx = args.indexOf("--src");
if (srcIdx < 0 || !args[srcIdx + 1]) {
  console.error("usage: node scripts/v3/port.mjs --src <cities-v-5 dir>");
  process.exit(1);
}
const SRC = path.resolve(args[srcIdx + 1]);

const read = (f) => fs.readFileSync(path.join(SRC, f), "utf8");
const write = (rel, text) => {
  const f = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(f), { recursive: true });
  fs.writeFileSync(f, text);
  console.log(`wrote ${rel} (${text.length.toLocaleString()} chars)`);
};
const copy = (from, rel) => {
  const f = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(f), { recursive: true });
  fs.copyFileSync(path.join(SRC, from), f);
  console.log(`copied ${rel}`);
};
const GEN = (what) =>
  `GENERATED by scripts/v3/port.mjs from cities-v-5/${what} on main. Do not edit by hand:\n` +
  `   re-run the script to re-sync (see src/legacy/README.md).`;

/* ---------- helpers that refuse to guess ---------- */

function indexOnce(text, needle, label) {
  const i = text.indexOf(needle);
  if (i < 0) throw new Error(`${label}: marker not found:\n${needle}`);
  if (text.indexOf(needle, i + 1) >= 0) throw new Error(`${label}: marker is not unique:\n${needle}`);
  return i;
}
/** replace one exact occurrence */
function subOnce(text, from, to, label) {
  const i = indexOnce(text, from, label);
  return text.slice(0, i) + to + text.slice(i + from.length);
}
/** replace every occurrence, insisting there are exactly `n` */
function subAll(text, from, to, n, label) {
  const count = text.split(from).length - 1;
  if (count !== n) throw new Error(`${label}: expected ${n} occurrences, found ${count}`);
  return text.split(from).join(to);
}
/** replace everything from the line that starts with `fromLine` up to (not
 *  including) the line that starts with `toLine` */
function cutBetween(text, fromLine, toLine, replacement, label) {
  const a = indexOnce(text, "\n" + fromLine, `${label} (from)`) + 1;
  const b = indexOnce(text, "\n" + toLine, `${label} (to)`) + 1;
  if (b <= a) throw new Error(`${label}: markers out of order`);
  return text.slice(0, a) + replacement + text.slice(b);
}
const lines = (...ls) => ls.join("\n");

/* ====================================================================
   1 · markup: the whole body, with slots where React draws
   ==================================================================== */

const html = read("index.html");
const LN = html.split("\n");
const lineOf = (needle, from = 0) => {
  const i = LN.findIndex((l, k) => k >= from && l.includes(needle));
  if (i < 0) throw new Error(`markup marker not found: ${needle}`);
  return i;
};

const iBody = lineOf("<body>");
const iScripts = lineOf('<script src="');
const iConstraints = lineOf("<!-- 4 Constraints Diagnosis (empty) -->");
const iLevers = lineOf("<!-- 5 Levers for Change (empty) -->");
const iExplainers = lineOf('<div class="explainers-view" id="explainersView">');
const iExplainersEnd = LN.findIndex((l, k) => k > iExplainers && l === "  </div>");
if (iExplainersEnd < 0) throw new Error("explainers view: closing </div> not found");
if (!(iBody < iConstraints && iConstraints < iLevers && iLevers < iExplainers && iExplainersEnd < iScripts))
  throw new Error("markup markers out of order");

let body = [
  ...LN.slice(iBody + 1, iConstraints),
  /* Constraints Diagnosis is this branch's own section: React renders it
     here. .sec-root marks it as the section's top-level element for the
     switch. */
  '      <!-- 4 Constraints Diagnosis: this branch\'s React section (src/components/ConstraintsSection.tsx) -->',
  '      <div id="constraints-slot" class="sec-root"></div>',
  "",
  ...LN.slice(iLevers, iExplainers),
  /* the Explainers content is React's too (src/components/ExplainersContent.tsx) */
  '  <div class="explainers-view" id="explainersView"></div>',
  ...LN.slice(iExplainersEnd + 1, iScripts),
].join("\n") + "\n";

/* the rail (hidden, but the source of truth for every section's steps) lists
   this branch's constraints steps instead of main's placeholder pages */
body = subOnce(body,
  '<div class="sec" data-sec="page-constraints page-city-in-metro page-constraints-lorem">',
  '<div class="sec" data-sec="page-constraints page-constraints-diagnose page-branch-analysis">',
  "rail: constraints section");
body = subOnce(body,
  lines('          <li data-step="page-constraints"><span class="dot"></span><button onclick="goTo(\'page-constraints\')">How is the metro performing?</button></li>',
        '          <li data-step="page-city-in-metro"><span class="dot"></span><button onclick="goTo(\'page-city-in-metro\')">Is your city pulling with the metro?</button></li>',
        '          <li data-step="page-constraints-lorem"><span class="dot"></span><button onclick="goTo(\'page-constraints-lorem\')">Lorem Ipsum</button></li>'),
  lines('          <li data-step="page-constraints"><span class="dot"></span><button onclick="goTo(\'page-constraints\')">Where is your constraint?</button></li>',
        '          <li data-step="page-constraints-diagnose"><span class="dot"></span><button onclick="goTo(\'page-constraints-diagnose\')">How we diagnose the constraint</button></li>',
        '          <li data-step="page-branch-analysis"><span class="dot"></span><button onclick="goTo(\'page-branch-analysis\')">Branch analysis</button></li>'),
  "rail: constraints steps");

/* the closes are gone from the last two sections (Sept 2026, the user's
   call: "remove test your knowledge and put your insights section at the
   end of constraints section and levers for change section") — so their
   rail steps go too, which is also what the journey window lists. The
   first three sections keep theirs. */
body = subOnce(body,
  lines('          <li data-step="check-constraints"><span class="dot"></span><button onclick="goTo(\'check-constraints\')">Test your knowledge</button></li>',
        '          <li data-step="apply-constraints"><span class="dot"></span><button onclick="goTo(\'apply-constraints\')">Put your insights</button></li>',
        "        </ul>"),
  "        </ul>",
  "rail: no close on constraints");
body = subOnce(body,
  lines('          <li data-step="check-levers"><span class="dot"></span><button onclick="goTo(\'check-levers\')">Test your knowledge</button></li>',
        '          <li data-step="apply-levers"><span class="dot"></span><button onclick="goTo(\'apply-levers\')">Put your insights</button></li>',
        "        </ul>"),
  "        </ul>",
  "rail: no close on levers");

/* Levers for Change carries no copy yet (Sept 2026, the user's call:
   "remove text in levers for change section") — main's line described a
   chapter still being drafted and pointed at the closing checks, which are
   no longer under it either */
body = subOnce(body,
  lines("          <h2>Levers for Change</h2>",
        "        </div>",
        '        <p class="lede">What could loosen the constraint the diagnosis points to. This chapter&rsquo;s content is still being drafted &mdash; its closing checks below already work.</p>'),
  lines("          <h2>Levers for Change</h2>",
        "        </div>",
        /* …and a placeholder block in its place, in main's own dashed-frame
           idiom (.placeholder-frame, which its stylesheet still carries).
           No .ph-title: main sets that in caps, and nothing authored here
           is set in caps. */
        '        <div class="placeholder-frame">',
        '          <span class="ph-sub">[placeholder: the levers for the constraint the diagnosis lands on, and what each one asks for]</span>',
        "        </div>"),
  "levers: a placeholder block");

/* the Explainers button comes back to the masthead (main keeps its styles and
   toggleExplainers() looks for #explainersBtn, but dropped it from the markup);
   the book is the one the explainers page header draws */
const BOOK =
  '<svg viewBox="0 0 95.1 79.5" fill="currentColor" aria-hidden="true"><path d="M93,23h-8.4v-5.2c0-1.1-.9-2-2-2-12.1,0-24,2.4-35.2,7-11.2-4.7-23-7-35.2-7-1.1,0-2,.9-2,2v5.2H2c-1.1,0-2,.9-2,2v52.5c0,1.1.9,2,2,2h91.1c1.1,0,2-.9,2-2V25c-.1-1.1-1-2-2.1-2ZM3.9,75.5V26.9h6.5v43.3c0,1.1.9,2,2,2,8,0,15.8,1.2,23.4,3.3H3.9ZM45.5,74.6c-10-3.9-20.5-6.1-31.3-6.3V19.8c10.9.2,21.3,2.4,31.3,6.5v48.3ZM49.5,26.3c10-4.1,20.5-6.3,31.3-6.6v48.6c-10.9.3-21.3,2.4-31.3,6.3V26.3ZM91.1,75.5h-31.9c7.6-2.1,15.4-3.3,23.4-3.3,1.1,0,2-.9,2-2V26.9h6.5v48.6Z"/></svg>';
body = subOnce(body,
  lines('        <div class="spacer"></div>',
        '        <nav class="toolbar-links">'),
  lines('        <div class="spacer"></div>',
        '        <button class="explainers-btn" id="explainersBtn" onclick="toggleExplainers()">' + BOOK + 'Explainers</button>',
        '        <nav class="toolbar-links">'),
  "masthead: explainers button");

/* the city list is this branch's: the cities the diagnostic pathway has data for
   (src/data/content.ts) — Boston, the one real city, and since 2026-09-24
   three PLACEHOLDER cities with made-up dials, one per ending Boston does
   not take (src/data/placeholderCities.ts; their landing verdicts are the
   "city hints" patch below). Main's own list (Boston and four more) names
   cities nothing here can diagnose. Keep this list in step with CITIES in
   content.ts. */
const CITY_OPTIONS = /( *)<option>Boston, United States of America<\/option>\n(?: *<option>[^<\n]*<\/option>\n){4}/g;
const optionMatches = body.match(CITY_OPTIONS);
if (!optionMatches || optionMatches.length !== 2) throw new Error(`city selects: expected 2 option lists, found ${optionMatches?.length ?? 0}`);
body = body.replace(CITY_OPTIONS, (m, indent) => [
  "Boston, United States of America",
  "City A, United States of America",
  "City B, United States of America",
  "City C, United States of America",
].map((c) => `${indent}<option${c.startsWith("Boston") ? " selected" : ""}>${c}</option>`).join("\n") + "\n");

/* assets and the framed page moved under public/legacy */
body = subAll(body, 'src="assets/gl_logo.png"', 'src="legacy/assets/gl_logo.png"', 2, "logo paths");
body = subOnce(body, 'src="rca-distributions.html?', 'src="legacy/rca-distributions.html?', "extras iframe src");

write("src/legacy/html/body.html", `<!-- ${GEN("index.html <body>")} -->\n` + body);

/* ====================================================================
   2 · stylesheet: verbatim, but the landing image comes through a bundled
       import (src/legacy/index.ts sets --map-asset)
   ==================================================================== */

let css = html.slice(html.indexOf("<style>") + "<style>".length, html.indexOf("</style>"));
css = subAll(css, 'url("assets/landing-page.webp")', "var(--map-asset)", 2, "landing image url");
write("src/legacy/v3.css", `/* ${GEN("index.html <style>")} */\n` + css);

/* ====================================================================
   3 · treemap.js: the IIFE becomes a function that returns its init()
   ==================================================================== */

let tm = read("treemap.js");
const tmOpen = /^\(function\(\)\{\n/m;
if (!tmOpen.test(tm)) throw new Error("treemap.js: opening IIFE not found");
tm = tm.replace(
  tmOpen,
  `/* ${GEN("treemap.js")} */\nimport * as d3 from "d3";\n\n` +
    "/* [port] the IIFE is a function returning its init(), which main ran on\n" +
    "   DOMContentLoaded and src/legacy/index.ts runs once the page is mounted */\n" +
    "export function loadTreemaps(){\n",
);
const tmTail =
  /\n  if \(document\.readyState === "loading"\) \{\n    document\.addEventListener\("DOMContentLoaded", init\);\n  \} else \{\n    init\(\);\n  \}\n\}\)\(\);\n*$/;
if (!tmTail.test(tm)) throw new Error("treemap.js: closing readyState block not found");
tm = tm.replace(tmTail, "\n  return init;\n}\n");
tm = subOnce(tm,
  '"rca-distributions.html?dots=peers&design="',
  '"legacy/rca-distributions.html?dots=peers&design="',
  "treemap.js dist frame url");
write("src/legacy/treemap.js", tm);

write("src/legacy/xch_geo.js", `/* ${GEN("data/geo/xch_geo.js")} */\n` + read("data/geo/xch_geo.js"));
/* the metro's industry rows (2024, and 2014 at the same grain): each file
   assigns one window global, which treemap.js and the page read */
for (const f of ["industries-2024.js", "industries-2014.js"])
  write(`src/legacy/${f}`, `/* ${GEN(f)} */\n` + read(f));
write("public/legacy/rca-distributions.html", read("rca-distributions.html"));
copy("assets/gl_logo.png", "public/legacy/assets/gl_logo.png");
copy("assets/landing-page.webp", "src/legacy/assets/landing-page.webp");

/* ====================================================================
   4 · the page scripts: wrapped as one module, told where React is
   ==================================================================== */

const starts = LN.map((l, i) => (l === "<script>" ? i : -1)).filter((i) => i >= 0);
const ends = LN.map((l, i) => (l === "</script>" ? i : -1)).filter((i) => i >= 0);
if (starts.length !== 2 || ends.length !== 2) throw new Error(`expected two inline scripts, found ${starts.length}`);
const script1 = LN.slice(starts[0] + 1, ends[0]).join("\n");
const script2 = LN.slice(starts[1] + 1, ends[1]).join("\n");

/* [type, label, ...args]: "sub" replaces one exact string; "suball" replaces
   every occurrence, insisting on exactly n of them; "cut" replaces the block
   from one line to the line before another. Applied in order. */
const PAGE_PATCHES = [
  ["sub", "collapsibles run now",
    lines('  window.addEventListener("load", () => {',
          "    setTimeout(initCollapsible, 200);",
          "  });"),
    lines("  /* [port] the page has long loaded by the time this runs: same delay, no event */",
          "  setTimeout(initCollapsible, 200);")],

  /* Constraints Diagnosis is this branch's section: its pages are the anchors
     the React scrolly carries and the branch-analysis page after it */
  ["sub", "pageIds: constraints pages (and Extras, which main left out of its spy)",
    '"page-constraints","page-city-in-metro","page-constraints-lorem","page-levers"];',
    '"page-constraints","page-constraints-diagnose","page-branch-analysis","page-levers","page-extras"];   /* [port] */'],
  ["sub", "sectionDefs: constraints pages, no close",
    '{name:"Constraints Diagnosis",pages:["page-constraints","page-city-in-metro","page-constraints-lorem","check-constraints","apply-constraints"],entry:"page-constraints"},',
    '{name:"Constraints Diagnosis",pages:["page-constraints","page-constraints-diagnose","page-branch-analysis"],entry:"page-constraints"},   /* [port] */'],

  /* …and so does Levers for Change: neither section closes on a quiz any
     more (Sept 2026, the user's call) */
  ["sub", "sectionDefs: levers pages, no close",
    '{name:"Levers for Change",pages:["page-levers","check-levers","apply-levers"], entry:"page-levers"},',
    '{name:"Levers for Change",pages:["page-levers"], entry:"page-levers"},   /* [port] */'],

  /* the section switch hides a section by its top-level element; the React
     section's anchors live inside one slot, which is that element */
  ["sub", "section switch: the constraints slot",
    '                   return el && (el.closest(".ov-wrap") || el); })',
    '                   return el && (el.closest(".ov-wrap, .sec-root") || el); })   /* [port] */'],

  /* main's rail highlight looks a rail step up by id, which finds nothing
     once a section is built as a scrolly (the step's own element is
     display:none there) and so falls back to the page; the tab ticks
     already resolve through the scrolly engines — the highlight, which
     feeds the URL hash here, does the same */
  ["sub", "rail highlight resolves scrolly steps",
    "      const el=document.getElementById(li.dataset.step);\n      if(!el) return;\n      const r=el.getBoundingClientRect();\n      if(r.top<=mid && r.bottom>=mid && r.height<bestHeight){",
    "      const el=(window.ovStepFor && window.ovStepFor(li.dataset.step)) ||\n        (window.ctStepFor && window.ctStepFor(li.dataset.step)) || document.getElementById(li.dataset.step);   /* [port] */\n      if(!el) return;\n      const r=el.getBoundingClientRect();\n      if(r.top<=mid && r.bottom>=mid && r.height<bestHeight){"],

  /* the pager's line is the STORYLINE's five sections. Main already keeps
     Extras out of the tab strip ("the extras sit outside the storyline")
     but left it on the pager's line as a sixth stop. The Previous / Next
     cards are untouched, so the pager is still the way in and out of
     Extras; while the reader is there, no stop is past or current. */
  ["sub", "pager: five stops, not six",
    lines("    const stops = SECTIONS.map((sec, k) =>",
          '      (k ? \'<i class="pgr-seg\' + (k <= i ? " is-past" : "") + \'"></i>\' : "") +',
          '      \'<button type="button" class="pgr-stop\' + (k < i ? " is-past" : k === i ? " is-cur" : "") +',
          '      \'" data-go="\' + k + \'" title="\' + sec.name + \'" aria-label="\' + sec.name + \'"\' +',
          "      (k === i ? ' aria-current=\"step\"' : '') + '>' +",
          "      (k < i ? CHECK : '<span>' + (k + 1) + '</span>') + '</button>').join(\"\");"),
    lines("    /* [port] the storyline is the five; Extras is not a stop on it */",
          '    const STORY = SECTIONS.filter(sec => sec.name !== "Extras");   /* [port] */',
          "    const iCur = STORY.indexOf(SECTIONS[i]);   /* [port] -1 on Extras */",
          "    const stops = STORY.map((sec, k) =>",
          '      (k ? \'<i class="pgr-seg\' + (iCur >= 0 && k <= iCur ? " is-past" : "") + \'"></i>\' : "") +',
          '      \'<button type="button" class="pgr-stop\' + (iCur >= 0 && k < iCur ? " is-past" : k === iCur ? " is-cur" : "") +',
          '      \'" data-go="\' + SECTIONS.indexOf(sec) + \'" title="\' + sec.name + \'" aria-label="\' + sec.name + \'"\' +',
          "      (k === iCur ? ' aria-current=\"step\"' : '') + '>' +",
          "      (iCur >= 0 && k < iCur ? CHECK : '<span>' + (k + 1) + '</span>') + '</button>').join(\"\");")],

  /* the last two sections no longer close on a quiz + insight (Sept 2026,
     the user's call). Upstream's data is left whole — a re-sync still picks
     up its wording — and the two are dropped on the way out, so both
     renderSecClose and wireSecClose find nothing and draw nothing. */
  ["sub", "no close on the last two sections",
    "  function sectionChecksData(){\n    return {",
    lines('  /* [port] Constraints Diagnosis and Levers for Change carry no close */',
          '  var NO_CLOSE = ["Constraints Diagnosis", "Levers for Change"];',
          "  function sectionChecksData(){",
          "    var all = sectionChecksDataUpstream();",
          "    NO_CLOSE.forEach(function(n){ delete all[n]; });",
          "    return all;",
          "  }",
          "  function sectionChecksDataUpstream(){",
          "    return {")],

  /* the sample journey state names a city the picker no longer offers, and
     the picker's other cities are placeholders, so no second one is seeded */
  ["sub", "sample explored cities",
    '  exploredCities.add("Chicago, United States of America");',
    '  /* [port] main seeds a second explored city here (Chicago); this branch has Boston and three placeholder cities */'],

  ["sub", "inview observer guard",
    "  pageIds.forEach(id=>observer.observe(document.getElementById(id)));",
    "  pageIds.forEach(id=>{ const el=document.getElementById(id); if(el) observer.observe(el); });   /* [port] */"],

  /* what React needs to hear: the page in view (for the URL hash), the
     Explainers tab, and the city */
  ["sub", "rail highlight tells React",
    lines("    currentPageId=bestId;",
          "    currentStepId=stepId;",
          "    visitedPages.add(bestId);"),
    lines("    currentPageId=bestId;",
          "    currentStepId=stepId;",
          "    visitedPages.add(bestId);",
          "    if(window.__cities) window.__cities.onPage(stepId);   /* [port] */")],
  ["sub", "explainers toggle tells React",
    lines('    body.style.display=open?"none":"flex";',
          '    btn.classList.toggle("active",open);',
          "  }"),
    lines('    body.style.display=open?"none":"flex";',
          '    if(btn) btn.classList.toggle("active",open);',
          "    if(window.__cities) window.__cities.onExplainers(open);   /* [port] */",
          "  }")],
  ["sub", "city sync tells React",
    lines('    document.querySelectorAll(".city-short").forEach(el=>el.textContent=v.split(",")[0]);',
          "  }",
          "  /* scrolling down on the landing flows into City Overview */"),
    lines('    document.querySelectorAll(".city-short").forEach(el=>el.textContent=v.split(",")[0]);',
          "    if(window.__cities) window.__cities.onCity(v);   /* [port] */",
          "  }",
          "  /* scrolling down on the landing flows into City Overview */")],

  /* the landing teaser needs a verdict per city — the picker's menu reads
     CITY_HINTS[city].dir for every option, so a city without one throws.
     Main's own table covers Boston; the three placeholder cities take theirs
     from src/data/placeholderCities.ts — the same made-up place dials the
     walk reads, so the landing's city type and the walk's diagnosis agree
     (City A a Magnet, City B a Sponge, City C a Leak). Change the two
     together. */
  ["sub", "city hints for the placeholder cities",
    '    "Boston, United States of America":  { dir:"up",   rate: 0.3, pay: 5.1, word:"growing slowly", head:"<strong>Boston is growing slowly</strong>" },',
    lines('    "Boston, United States of America":  { dir:"up",   rate: 0.3, pay: 5.1, word:"growing slowly", head:"<strong>Boston is growing slowly</strong>" },',
          '    /* [port] this branch\'s placeholder cities, from src/data/placeholderCities.ts: made-up dials, one ending each */',
          '    "City A, United States of America":  { dir:"up",   rate: 1.6, pay: 4.8, word:"growing fast",   head:"<strong>City A is growing fast</strong>" },',
          '    "City B, United States of America":  { dir:"up",   rate: 1.8, pay: 2.4, word:"growing fast",   head:"<strong>City B is growing fast</strong>" },',
          '    "City C, United States of America":  { dir:"down", rate:-0.5, pay: 2.5, word:"shrinking",      head:"<strong>City C is shrinking</strong>" },')],

  ["sub", "intro skip button init runs now",
    lines('  document.addEventListener("DOMContentLoaded", ()=>{',
          "    const skipBtn=document.querySelector('.intro-skip');"),
    lines("  (()=>{   /* [port] runs now: the document loaded long ago */",
          "    const skipBtn=document.querySelector('.intro-skip');")],
  ["sub", "intro skip button init closes",
    lines("      skipBtn.classList.toggle('hidden', !isIntroPage);",
          "    }",
          "  });"),
    lines("      skipBtn.classList.toggle('hidden', !isIntroPage);",
          "    }",
          "  })();")],

  /* Small screens: until 2026-09-17 this list also carried a layer for
     narrow screens (the landing's wheel/swipe entry, short tab names, the
     city chip in two spans, the active tab centred in its strip, the
     scrolly spies reading under a stacked stage, a phone floor for the
     population chart), with the CSS side in src/legacy/port.css. Main's
     v-1 has since taken all of that on in its own way (breakpoints at
     1199 / 899 / 599, .secnav-lbl, .cp-rest, landingAtEnd(), its own tab
     centring in showSection), so the port carries none of it now — with
     one exception, the section menu on phones, below. */

  /* ---- the section menu on phones (2026-09-17; a candidate for main) ----
     Main keeps its tab strip at every width and lets it scroll on a phone,
     where it has ~165px beside the location chip: only the current tab is
     in view, the rest are cut, and nothing says the strip moves. At main's
     mobile tier (≤599px, src/legacy/port.css) the strip stands down and the
     sections collapse into one control in the chip's family: a button
     naming the section you are on, and a menu of the five in the tabs' own
     state language (a check behind you, the current one on the tint,
     numbers ahead). Built beside the tabs; rendered by showSection. */
  ["sub", "section menu built beside the tabs",
    lines("    b.addEventListener(\"click\", () => showSection(i));",
          "    secNavEl.appendChild(b);",
          "  });"),
    lines("    b.addEventListener(\"click\", () => showSection(i));",
          "    secNavEl.appendChild(b);",
          "  });",
          "  /* [port] on phones the tab strip stands down (src/legacy/port.css) and the",
          "     sections collapse into one control beside the location chip: a button",
          "     naming the section you are on, and a menu of the five in the tabs' own",
          "     state language. showSection renders both. */",
          "  var secMenuWrap = document.createElement(\"div\");",
          "  secMenuWrap.className = \"secmenu\";",
          "  secMenuWrap.innerHTML =",
          "    '<button type=\"button\" class=\"secmenu-btn\" aria-haspopup=\"menu\" aria-expanded=\"false\">' +",
          "    '<span class=\"num\"></span><span class=\"secmenu-lbl\"></span></button>' +",
          "    '<div class=\"secmenu-list\" role=\"menu\" aria-label=\"Sections\" hidden></div>';",
          "  secNavEl.insertAdjacentElement(\"afterend\", secMenuWrap);",
          "  var secMenuBtn = secMenuWrap.querySelector(\".secmenu-btn\");",
          "  var secMenuList = secMenuWrap.querySelector(\".secmenu-list\");",
          "  function closeSecMenu(){ secMenuList.hidden = true; secMenuBtn.setAttribute(\"aria-expanded\", \"false\"); }",
          "  secMenuBtn.addEventListener(\"click\", () => {",
          "    var open = secMenuList.hidden;",
          "    secMenuList.hidden = !open;",
          "    secMenuBtn.setAttribute(\"aria-expanded\", String(open));",
          "  });",
          "  secMenuList.addEventListener(\"click\", e => {",
          "    var b = e.target.closest(\"[data-go]\");",
          "    if(!b) return;",
          "    closeSecMenu();",
          "    showSection(+b.dataset.go);",
          "  });",
          "  document.addEventListener(\"click\", e => { if(!secMenuWrap.contains(e.target)) closeSecMenu(); });",
          "  document.addEventListener(\"keydown\", e => {",
          "    if(e.key === \"Escape\" && !secMenuList.hidden){ closeSecMenu(); secMenuBtn.focus(); }",
          "  });",
          "  function renderSecMenu(i){",
          "    if(!secMenuList) return;",
          "    var CHECK = '<svg viewBox=\"0 0 10 8\" width=\"9\" height=\"7\" aria-hidden=\"true\"><path d=\"M1 4.2 3.7 6.8 9 1.2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/></svg>';",
          "    secMenuBtn.querySelector(\".num\").textContent = String(i + 1);",
          "    secMenuBtn.querySelector(\".secmenu-lbl\").textContent = SECTIONS[i].name;",
          "    secMenuList.innerHTML = SECTIONS.map((sec, k) =>",
          "      /* the extras sit outside the storyline: listed only while the reader",
          "         is there, as on the tabs */",
          "      (sec.name === \"Extras\" && k !== i) ? \"\" :",
          "      '<button type=\"button\" class=\"secmenu-opt' + (k < i ? \" is-done\" : k === i ? \" is-on\" : \"\") +",
          "      '\" role=\"menuitem\" data-go=\"' + k + '\"' + (k === i ? ' aria-current=\"page\"' : \"\") + '>' +",
          "      '<span class=\"num\">' + (k < i ? CHECK : String(k + 1)) + '</span><span>' + sec.name + '</span></button>'",
          "    ).join(\"\");",
          "    closeSecMenu();",
          "  }")],
  ["sub", "section switch renders the menu",
    lines("      if(k === i) b.setAttribute(\"aria-current\", \"page\");",
          "      else b.removeAttribute(\"aria-current\");",
          "    });",
          "    fitSecNav();"),
    lines("      if(k === i) b.setAttribute(\"aria-current\", \"page\");",
          "      else b.removeAttribute(\"aria-current\");",
          "    });",
          "    renderSecMenu(i);   /* [port] the phone's section menu, beside the tabs */",
          "    fitSecNav();")],

  /* ---- site-level layout variants (2026-09-21; src/site/) ----
     A study of how the tool's two halves — the three sections that describe
     the city, and the two that diagnose it and act — are organised and how
     the reader crosses from one to the other. Main's switch shows one
     section at a time and scrolls to its top; the variants need it to be
     able to keep several sections up at once (one scroll), to aim at a
     section's start instead of the page's, and to say which section it is
     on. Each of those is a question the switch asks of window.__cities, and
     every one falls back to main's behaviour when nothing answers — so with
     no variant chosen the page is main's "pages" layout, exactly.

     Since 2026-09-30 main's v-5 carries a layout study of its own, modelled
     on this one (a pill, ?layout=scroll, a teal close under each section, a
     band before part two). It stays in the page, dormant: the layout is
     held at "pages" below and its pill is hidden (src/legacy/port.css), so
     the study the reader sees is this branch's and the two never run at
     once. Main's part names over the tabs are NOT part of that — they show
     in every layout, and replace the ones src/styles/site.css used to print. */
  ["sub", "site variants: main's own layout study stays on \"pages\"",
    '  setSiteLayout(new URLSearchParams(location.search).get("layout") === "scroll" ? "scroll" : "pages", true);',
    '  setSiteLayout("pages", true);   /* [port] this branch\'s study (?site=) decides the layout */'],
  ["sub", "site variants: what the switch asks of React",
    "  function showSection(i, toTop){",
    lines("  /* [port] the site-level layout variants (src/site/): which sections stay up",
          "     with section i, and where a switch scrolls to. Unanswered, each is main's",
          "     own behaviour. */",
          "  const siteHook = name => window.__cities && window.__cities[name];",
          "  const secHidden = (k, i) => siteHook(\"sectionHidden\") ? window.__cities.sectionHidden(k, i) : k !== i;",
          "  function showSection(i, toTop){")],
  ["sub", "site variants: which sections stay up",
    "      sec.els.forEach(el => el.classList.toggle(\"sec-off\", scrollL && k < EXTRAS && i < EXTRAS ? false : k !== i)));",
    "      sec.els.forEach(el => el.classList.toggle(\"sec-off\", secHidden(k, i))));   /* [port] */"],
  ["sub", "site variants: where a switch scrolls to",
    "    if(toTop !== false){",
    lines("    /* [port] a variant that keeps several sections up aims at this one's start */",
          "    if(toTop !== false && siteHook(\"sectionScroll\") && window.__cities.sectionScroll(i)) toTop = false;",
          "    if(toTop !== false){")],
  ["sub", "site variants: the section the switch landed on",
    "    if (!scrollL || i === EXTRAS || prevSec === EXTRAS || prevSec < 0) window.dispatchEvent(new Event(\"resize\"));",
    lines("    if (!scrollL || i === EXTRAS || prevSec === EXTRAS || prevSec < 0) window.dispatchEvent(new Event(\"resize\"));",
          "    if(siteHook(\"onSection\")) window.__cities.onSection(i);   /* [port] */")],
  /* main folds a section's quiz into a dialog its pager opens, and sends a
     rail or journey step for a check there too. Where this branch's
     layouts close each section in the page, the step's own element exists
     and goTo scrolls to it — a second copy in a dialog would share its ids. */
  ["sub", "site variants: a check step scrolls to the inline close where there is one",
    "    if (/^(check|apply)-/.test(id) && window.openSecCheck) window.openSecCheck(true);",
    "    if (/^(check|apply)-/.test(id) && window.openSecCheck && !(window.__cities && window.__cities.closesInline)) window.openSecCheck(true);   /* [port] */"],
  /* main finds "the" close with a class lookup, which holds while the pager
     carries the only one; with a close under every section each is found
     through the id it already carries (check-<slug>) */
  ["sub", "site variants: a close is found by its own id",
    "  function wireSecClose(name){",
    lines("  /* [port] one close per section in the one-scroll layouts: found by the id it carries */",
          "  function secCloseRoot(c){",
          "    const t = c && document.getElementById(\"check-\" + c.slug);",
          "    return t ? t.closest(\".sec-close\") : null;",
          "  }",
          "  function wireSecClose(name){")],
  ["sub", "site variants: wiring reads that close",
    "    const root = document.querySelector(\".sec-close\");",
    "    const root = secCloseRoot(c);   /* [port] */"],
  ["sub", "site variants: a re-render replaces that close",
    "      const cur = document.querySelector(\".sec-close\");",
    "      const cur = secCloseRoot(c);   /* [port] */"],
  /* …and so does the focus main puts back after each re-render */
  ["sub", "site variants: focus returns to that close (the control)",
    "        let n = document.querySelector(\".sec-close \" + again);",
    "        let n = (secCloseRoot(c) || document).querySelector(again);   /* [port] */"],
  ["sub", "site variants: focus returns to that close (the dot)",
    "        if (!n || n.disabled) n = document.querySelector(\".sec-close .kc-dot.on\");",
    "        if (!n || n.disabled) n = (secCloseRoot(c) || document).querySelector(\".kc-dot.on\");   /* [port] */"],
  ["sub", "site variants: focus follows to the next question in that close",
    lines("            const cur = document.querySelector(\".sec-close\"), wasIn = !!(cur && cur.contains(document.activeElement));",
          "            st.qIdx = next; rerender();",
          "            if (wasIn){ const qEl = document.querySelector(\".sec-close .kc-slide:not([inert]) .ktest-q\"); if (qEl) qEl.focus({ preventScroll: true }); }"),
    lines("            const cur = secCloseRoot(c), wasIn = !!(cur && cur.contains(document.activeElement));   /* [port] */",
          "            st.qIdx = next; rerender();",
          "            if (wasIn){ const qEl = (secCloseRoot(c) || document).querySelector(\".kc-slide:not([inert]) .ktest-q\"); if (qEl) qEl.focus({ preventScroll: true }); }   /* [port] */")],

  /* main's teal closes ("What to take with you") are the breaks between
     sections in this branch's two-scroll layout (src/styles/site.css shows
     them there). Three of them close main's own sections and come across
     as written. The other two would close Constraints Diagnosis and Levers
     for Change with take-aways drafted for MAIN's versions of those
     sections ("housing as the wall", zoning and permitting) — this
     branch's diagnosis lands elsewhere and its levers are not written — so
     those two say what belongs there instead of saying it. */
  ["sub", "closes: sections 4 and 5 are this branch's, their take-aways are placeholders",
    "  const SEAL_ARROW = ",
    lines('  /* [port] main\'s points describe its own drafts of these two sections */',
          '  SEAL_POINTS["Constraints Diagnosis"] = ["[placeholder: what to take from the diagnosis]"];',
          '  SEAL_POINTS["Levers for Change"] = ["[placeholder: what to take from the levers]"];',
          "  const SEAL_ARROW = ")],

  /* ---- the address bar is this branch's (src/App.tsx) ----
     Main's v-5 writes the current section into the hash (#metro-industries)
     and routes from it. This branch already keeps a hash of its own, finer
     than a section (the page or rail step in view, an explainer) and with
     push / replace chosen per navigation, so main's writer and router stand
     down: two of them on one address bar overwrite each other. The slugs
     and window.sectionLinks stay, unused. */
  ["sub", "hash: main's writer stands down",
    lines("  function syncSectionHash(){",
          "    if (!SECTION_SLUGS || !toolIsOpen() || activeSec < 0 || !SECTION_SLUGS[activeSec]) return;"),
    lines("  function syncSectionHash(){",
          "    return;   /* [port] src/App.tsx owns the hash */",
          "    if (!SECTION_SLUGS || !toolIsOpen() || activeSec < 0 || !SECTION_SLUGS[activeSec]) return;")],
  ["sub", "hash: main's router stands down",
    lines("  const backToLandingRouted = backToLanding;",
          "  backToLanding = function(){",
          "    backToLandingRouted();",
          "    if (location.hash) history.replaceState(null, \"\", location.pathname + location.search);",
          "  };",
          "  window.addEventListener(\"hashchange\", () => routeFromHash(false));",
          "  if (document.readyState === \"complete\") routeFromHash(true);",
          "  else window.addEventListener(\"load\", () => routeFromHash(true));"),
    "  /* [port] src/App.tsx routes from the hash and clears it on the landing; main's own router (routeFromHash) is left unwired */"],
];

/* the same, for the second inline script (the section scrollies); empty
   since main's own small-screen layout arrived (see the note above) */
const PAGE2_PATCHES = [];

function applyPatches(text, patches) {
  /* a re-sync usually moves several anchors at once: every patch is tried
     and the ones that no longer fit are reported together */
  const failed = [];
  for (const p of patches) {
    const [kind, label] = p;
    try {
      text = kind === "sub"
        ? subOnce(text, p[2], p[3], `patch "${label}"`)
        : kind === "suball"
          ? subAll(text, p[2], p[3], p[4], `patch "${label}"`)
          : cutBetween(text, p[2], p[3], p[4], `patch "${label}"`);
    } catch (e) {
      failed.push(e.message);
    }
  }
  if (failed.length) throw new Error(`${failed.length} patch(es) no longer fit:\n\n` + failed.join("\n\n"));
  return text;
}
const page = applyPatches(script1, PAGE_PATCHES);
const page2 = applyPatches(script2, PAGE2_PATCHES);

const pageModule = lines(
  `/* ${GEN("index.html (the two inline <script> blocks)")}`,
  "   Every departure from the upstream text is marked [port] and comes from",
  "   PAGE_PATCHES in that script. */",
  'import * as d3 from "d3";',
  'import * as L from "leaflet";',
  "",
  "/* [port] main's page loads d3 and Leaflet as <script src> globals, so its own",
  "   code is free to reach either off window — and in one place it does:",
  "   initPlacesInMetro guards on `window.d3`, so with it unset the places table,",
  "   its picker and the metro's cells on the map all stay empty, silently and with",
  "   no error. Leaflet's UMD build assigns itself on import; d3's ESM build does",
  "   not, so the port restores the global main's script runs against. */",
  "window.d3 = d3;",
  "",
  "/* [port] both inline scripts, in order, in one function scope: they shared the",
  "   page's global scope on main, and the second reads the first's declarations */",
  "export function initPage(){",
  page,
  "",
  "  /* [port] the React constraints scrolly tracks a sticky stage that no outside",
  "     measure can read, so it reports its own page the way updateActivePage does */",
  "  function markPage(id){",
  "    if(!pageIds.includes(id)) return;",
  "    currentPageId=id; currentStepId=id;",
  "    visitedPages.add(id);",
  "    if(window.__cities) window.__cities.onPage(id);",
  "  }",
  "",
  "  /* ===== [port] cities-v-1's second inline script starts here ===== */",
  page2,
  "",
  "  /* [port] what the markup's inline handlers reach for (the rerouted goTo and",
  "     enterTool, since this runs last), and what the React app drives */",
  "  Object.assign(window, { enterTool, backToLanding, goTo, toggleExplainers, introSlide,",
  "    lockSlider, lockDot, twPick, twBack, twReset, openGeoMap, closeGeoMap, closeJourney,",
  "    journeyGoTo, downloadInsights, sendChat, closeChat, downloadChatCsv,",
  "    submitPracticeOverview, submitPractice, shareViz });",
  "  return { syncCity, goTo, enterTool, backToLanding, toggleExplainers, openJourney, markPage, sectionDefs,",
  "    /* the site-level layout variants (src/site/) drive the switch and place the closes */",
  "    showSection, renderSecClose, wireSecClose };",
  "}",
  "",
);
write("src/legacy/v3-page.js", pageModule);

console.log("done");
