#!/usr/bin/env node
/* Port the cities-v-3 prototype (the static site on main) into this app.

   usage:  node scripts/v3/port.mjs --src <directory holding cities-v-3's files>

   e.g.    rm -rf /tmp/v3 && mkdir -p /tmp/v3 && git archive origin/main cities-v-3 | tar -x -C /tmp/v3
           node scripts/v3/port.mjs --src /tmp/v3/cities-v-3

   v-3 IS the app's shell: its landing, masthead, section tabs and pager,
   journey window, dialogs and every section but City Constraints come across
   as they are. React renders only City Constraints (and the Explainers
   content) into slots inside that markup. What it writes:

     src/legacy/html/body.html             v-3's <body>, with the slots and a few swaps (below)
     src/legacy/v3.css                     v-3's stylesheet, verbatim but for the landing image
     src/legacy/treemap.js                 treemap.js as a module: a function that returns its init()
     src/legacy/xch_geo.js                 the boundary data, verbatim
     src/legacy/v3-page.js                 the two inline scripts, wrapped as one module and patched
     src/legacy/assets/landing-page.webp   the landing image (bundled through an import)
     public/legacy/assets/gl_logo.png      the logo the markup references
     public/legacy/rca-distributions.html  the page the Extras section frames, verbatim

   Every edit to v-3's text is a step in this file, anchored on a line of the
   upstream text and asserted to match exactly once — so a re-sync that no
   longer fits fails loudly here rather than quietly in the browser. */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const args = process.argv.slice(2);
const srcIdx = args.indexOf("--src");
if (srcIdx < 0 || !args[srcIdx + 1]) {
  console.error("usage: node scripts/v3/port.mjs --src <cities-v-3 dir>");
  process.exit(1);
}
const SRC = path.resolve(args[srcIdx + 1]);

const read = (f) => fs.readFileSync(path.join(SRC, f), "utf8");
const write = (rel, text) => {
  const f = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(f), { recursive: true });
  fs.writeFileSync(f, text);
  console.log(`wrote ${rel} (${text.length.toLocaleString()} chars)`);
};
const copy = (from, rel) => {
  const f = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(f), { recursive: true });
  fs.copyFileSync(path.join(SRC, from), f);
  console.log(`copied ${rel}`);
};
const GEN = (what) =>
  `GENERATED by scripts/v3/port.mjs from cities-v-3/${what} on main. Do not edit by hand:\n` +
  `   re-run the script to re-sync (see src/legacy/README.md).`;

/* ---------- helpers that refuse to guess ---------- */

function indexOnce(text, needle, label) {
  const i = text.indexOf(needle);
  if (i < 0) throw new Error(`${label}: marker not found:\n${needle}`);
  if (text.indexOf(needle, i + 1) >= 0) throw new Error(`${label}: marker is not unique:\n${needle}`);
  return i;
}
/** replace one exact occurrence */
function subOnce(text, from, to, label) {
  const i = indexOnce(text, from, label);
  return text.slice(0, i) + to + text.slice(i + from.length);
}
/** replace every occurrence, insisting there are exactly `n` */
function subAll(text, from, to, n, label) {
  const count = text.split(from).length - 1;
  if (count !== n) throw new Error(`${label}: expected ${n} occurrences, found ${count}`);
  return text.split(from).join(to);
}
/** replace everything from the line that starts with `fromLine` up to (not
 *  including) the line that starts with `toLine` */
function cutBetween(text, fromLine, toLine, replacement, label) {
  const a = indexOnce(text, "\n" + fromLine, `${label} (from)`) + 1;
  const b = indexOnce(text, "\n" + toLine, `${label} (to)`) + 1;
  if (b <= a) throw new Error(`${label}: markers out of order`);
  return text.slice(0, a) + replacement + text.slice(b);
}
const lines = (...ls) => ls.join("\n");

/* ====================================================================
   1 · markup: the whole body, with slots where React draws
   ==================================================================== */

const html = read("index.html");
const LN = html.split("\n");
const lineOf = (needle, from = 0) => {
  const i = LN.findIndex((l, k) => k >= from && l.includes(needle));
  if (i < 0) throw new Error(`markup marker not found: ${needle}`);
  return i;
};

const iBody = lineOf("<body>");
const iScripts = lineOf('<script src="');
const iConstraints = lineOf("<!-- 4 City Constraints (empty) -->");
const iLevers = lineOf("<!-- 5 Levers for Change (empty) -->");
const iExplainers = lineOf('<div class="explainers-view" id="explainersView">');
const iExplainersEnd = LN.findIndex((l, k) => k > iExplainers && l === "  </div>");
if (iExplainersEnd < 0) throw new Error("explainers view: closing </div> not found");
if (!(iBody < iConstraints && iConstraints < iLevers && iLevers < iExplainers && iExplainersEnd < iScripts))
  throw new Error("markup markers out of order");

let body = [
  ...LN.slice(iBody + 1, iConstraints),
  /* City Constraints is this branch's own section: React renders it here.
     .sec-root marks it as the section's top-level element for the switch. */
  '      <!-- 4 City Constraints: this branch\'s React section (src/components/ConstraintsSection.tsx) -->',
  '      <div id="constraints-slot" class="sec-root"></div>',
  "",
  ...LN.slice(iLevers, iExplainers),
  /* the Explainers content is React's too (src/components/ExplainersContent.tsx) */
  '  <div class="explainers-view" id="explainersView"></div>',
  ...LN.slice(iExplainersEnd + 1, iScripts),
].join("\n") + "\n";

/* the rail (hidden, but the source of truth for every section's steps) lists
   this branch's constraints steps instead of v-3's placeholder pages */
body = subOnce(body,
  '<div class="sec" data-sec="page-constraints page-city-in-metro page-constraints-lorem">',
  '<div class="sec" data-sec="page-constraints page-constraints-diagnose page-branch-analysis">',
  "rail: constraints section");
body = subOnce(body,
  lines('          <li data-step="page-constraints"><span class="dot"></span><button onclick="goTo(\'page-constraints\')">How is the metro performing?</button></li>',
        '          <li data-step="page-city-in-metro"><span class="dot"></span><button onclick="goTo(\'page-city-in-metro\')">Is your city pulling with the metro?</button></li>',
        '          <li data-step="page-constraints-lorem"><span class="dot"></span><button onclick="goTo(\'page-constraints-lorem\')">Lorem Ipsum</button></li>'),
  lines('          <li data-step="page-constraints"><span class="dot"></span><button onclick="goTo(\'page-constraints\')">Where is your constraint?</button></li>',
        '          <li data-step="page-constraints-diagnose"><span class="dot"></span><button onclick="goTo(\'page-constraints-diagnose\')">How we diagnose the constraint</button></li>',
        '          <li data-step="page-branch-analysis"><span class="dot"></span><button onclick="goTo(\'page-branch-analysis\')">Branch analysis</button></li>'),
  "rail: constraints steps");

/* the Explainers button comes back to the masthead (v-3 keeps its styles and
   toggleExplainers() looks for #explainersBtn, but dropped it from the markup);
   the book is the one the explainers page header draws */
const BOOK =
  '<svg viewBox="0 0 95.1 79.5" fill="currentColor" aria-hidden="true"><path d="M93,23h-8.4v-5.2c0-1.1-.9-2-2-2-12.1,0-24,2.4-35.2,7-11.2-4.7-23-7-35.2-7-1.1,0-2,.9-2,2v5.2H2c-1.1,0-2,.9-2,2v52.5c0,1.1.9,2,2,2h91.1c1.1,0,2-.9,2-2V25c-.1-1.1-1-2-2.1-2ZM3.9,75.5V26.9h6.5v43.3c0,1.1.9,2,2,2,8,0,15.8,1.2,23.4,3.3H3.9ZM45.5,74.6c-10-3.9-20.5-6.1-31.3-6.3V19.8c10.9.2,21.3,2.4,31.3,6.5v48.3ZM49.5,26.3c10-4.1,20.5-6.3,31.3-6.6v48.6c-10.9.3-21.3,2.4-31.3,6.3V26.3ZM91.1,75.5h-31.9c7.6-2.1,15.4-3.3,23.4-3.3,1.1,0,2-.9,2-2V26.9h6.5v48.6Z"/></svg>';
body = subOnce(body,
  lines('        <div class="spacer"></div>',
        '        <nav class="toolbar-links">'),
  lines('        <div class="spacer"></div>',
        '        <button class="explainers-btn" id="explainersBtn" onclick="toggleExplainers()">' + BOOK + 'Explainers</button>',
        '        <nav class="toolbar-links">'),
  "masthead: explainers button");

/* the city list is this branch's: the four sample cities the diagnostic tree
   has data for (Boston stays the opening one) */
const CITY_OPTIONS = /( *)<option>Boston, United States of America<\/option>\n(?: *<option>[^<\n]*<\/option>\n){4}/g;
const optionMatches = body.match(CITY_OPTIONS);
if (!optionMatches || optionMatches.length !== 2) throw new Error(`city selects: expected 2 option lists, found ${optionMatches?.length ?? 0}`);
body = body.replace(CITY_OPTIONS, (m, indent) => [
  "Memphis, United States of America",
  "San Antonio, United States of America",
  "San Jose, United States of America",
  "Boston, United States of America",
].map((c) => `${indent}<option${c.startsWith("Boston") ? " selected" : ""}>${c}</option>`).join("\n") + "\n");

/* assets and the framed page moved under public/legacy */
body = subAll(body, 'src="assets/gl_logo.png"', 'src="legacy/assets/gl_logo.png"', 2, "logo paths");
body = subOnce(body, 'src="rca-distributions.html?', 'src="legacy/rca-distributions.html?', "extras iframe src");

write("src/legacy/html/body.html", `<!-- ${GEN("index.html <body>")} -->\n` + body);

/* ====================================================================
   2 · stylesheet: verbatim, but the landing image comes through a bundled
       import (src/legacy/index.ts sets --map-asset)
   ==================================================================== */

let css = html.slice(html.indexOf("<style>") + "<style>".length, html.indexOf("</style>"));
css = subAll(css, 'url("assets/landing-page.webp")', "var(--map-asset)", 2, "landing image url");
write("src/legacy/v3.css", `/* ${GEN("index.html <style>")} */\n` + css);

/* ====================================================================
   3 · treemap.js: the IIFE becomes a function that returns its init()
   ==================================================================== */

let tm = read("treemap.js");
const tmOpen = /^\(function\(\)\{\n/m;
if (!tmOpen.test(tm)) throw new Error("treemap.js: opening IIFE not found");
tm = tm.replace(
  tmOpen,
  `/* ${GEN("treemap.js")} */\nimport * as d3 from "d3";\n\n` +
    "/* [port] the IIFE is a function returning its init(), which main ran on\n" +
    "   DOMContentLoaded and src/legacy/index.ts runs once the page is mounted */\n" +
    "export function loadTreemaps(){\n",
);
const tmTail =
  /\n  if \(document\.readyState === "loading"\) \{\n    document\.addEventListener\("DOMContentLoaded", init\);\n  \} else \{\n    init\(\);\n  \}\n\}\)\(\);\n*$/;
if (!tmTail.test(tm)) throw new Error("treemap.js: closing readyState block not found");
tm = tm.replace(tmTail, "\n  return init;\n}\n");
tm = subOnce(tm,
  '"rca-distributions.html?dots=peers&design="',
  '"legacy/rca-distributions.html?dots=peers&design="',
  "treemap.js dist frame url");
write("src/legacy/treemap.js", tm);

write("src/legacy/xch_geo.js", `/* ${GEN("data/geo/xch_geo.js")} */\n` + read("data/geo/xch_geo.js"));
write("public/legacy/rca-distributions.html", read("rca-distributions.html"));
copy("assets/gl_logo.png", "public/legacy/assets/gl_logo.png");
copy("assets/landing-page.webp", "src/legacy/assets/landing-page.webp");

/* ====================================================================
   4 · the page scripts: wrapped as one module, told where React is
   ==================================================================== */

const starts = LN.map((l, i) => (l === "<script>" ? i : -1)).filter((i) => i >= 0);
const ends = LN.map((l, i) => (l === "</script>" ? i : -1)).filter((i) => i >= 0);
if (starts.length !== 2 || ends.length !== 2) throw new Error(`expected two inline scripts, found ${starts.length}`);
const script1 = LN.slice(starts[0] + 1, ends[0]).join("\n");
const script2 = LN.slice(starts[1] + 1, ends[1]).join("\n");

/* [type, label, ...args]: "sub" replaces one exact string; "suball" replaces
   every occurrence, insisting on exactly n of them; "cut" replaces the block
   from one line to the line before another. Applied in order. */
const PAGE_PATCHES = [
  ["sub", "collapsibles run now",
    lines('  window.addEventListener("load", () => {',
          "    setTimeout(initCollapsible, 200);",
          "  });"),
    lines("  /* [port] the page has long loaded by the time this runs: same delay, no event */",
          "  setTimeout(initCollapsible, 200);")],

  /* City Constraints is this branch's section: its pages are the anchors the
     React scrolly carries and the branch-analysis page after it */
  ["sub", "pageIds: constraints pages (and Extras, which v-3 left out of its spy)",
    '"page-constraints","page-city-in-metro","page-constraints-lorem","page-levers"];',
    '"page-constraints","page-constraints-diagnose","page-branch-analysis","page-levers","page-extras"];   /* [port] */'],
  ["sub", "sectionDefs: constraints pages",
    '{name:"City Constraints",pages:["page-constraints","page-city-in-metro","page-constraints-lorem","check-constraints","apply-constraints"],entry:"page-constraints"},',
    '{name:"City Constraints",pages:["page-constraints","page-constraints-diagnose","page-branch-analysis","check-constraints","apply-constraints"],entry:"page-constraints"},   /* [port] */'],

  /* the section switch hides a section by its top-level element; the React
     section's anchors live inside one slot, which is that element */
  ["sub", "section switch: the constraints slot",
    '                   return el && (el.closest(".ov-wrap") || el); })',
    '                   return el && (el.closest(".ov-wrap, .sec-root") || el); })   /* [port] */'],

  /* v-3's rail highlight looks a rail step up by id, which finds nothing
     once a section is built as a scrolly (the step's own element is
     display:none there) and so falls back to the page; the tab ticks
     already resolve through the scrolly engines — the highlight, which
     feeds the URL hash here, does the same */
  ["sub", "rail highlight resolves scrolly steps",
    "      const el=document.getElementById(li.dataset.step);\n      if(!el) return;\n      const r=el.getBoundingClientRect();\n      if(r.top<=mid && r.bottom>=mid && r.height<bestHeight){",
    "      const el=(window.ovStepFor && window.ovStepFor(li.dataset.step)) ||\n        (window.ctStepFor && window.ctStepFor(li.dataset.step)) || document.getElementById(li.dataset.step);   /* [port] */\n      if(!el) return;\n      const r=el.getBoundingClientRect();\n      if(r.top<=mid && r.bottom>=mid && r.height<bestHeight){"],

  /* the sample journey state names a city the picker no longer offers */
  ["sub", "sample explored cities",
    '  exploredCities.add("Chicago, United States of America");',
    '  exploredCities.add("Memphis, United States of America");   /* [port] */'],

  ["sub", "inview observer guard",
    "  pageIds.forEach(id=>observer.observe(document.getElementById(id)));",
    "  pageIds.forEach(id=>{ const el=document.getElementById(id); if(el) observer.observe(el); });   /* [port] */"],

  /* what React needs to hear: the page in view (for the URL hash), the
     Explainers tab, and the city */
  ["sub", "rail highlight tells React",
    lines("    currentPageId=bestId;",
          "    currentStepId=stepId;",
          "    visitedPages.add(bestId);"),
    lines("    currentPageId=bestId;",
          "    currentStepId=stepId;",
          "    visitedPages.add(bestId);",
          "    if(window.__cities) window.__cities.onPage(stepId);   /* [port] */")],
  ["sub", "explainers toggle tells React",
    lines('    body.style.display=open?"none":"flex";',
          '    btn.classList.toggle("active",open);',
          "  }"),
    lines('    body.style.display=open?"none":"flex";',
          '    if(btn) btn.classList.toggle("active",open);',
          "    if(window.__cities) window.__cities.onExplainers(open);   /* [port] */",
          "  }")],
  ["sub", "city sync tells React",
    lines('    document.querySelectorAll(".city-short").forEach(el=>el.textContent=v.split(",")[0]);',
          "  }",
          "  /* scrolling down on the landing flows into City Overview */"),
    lines('    document.querySelectorAll(".city-short").forEach(el=>el.textContent=v.split(",")[0]);',
          "    if(window.__cities) window.__cities.onCity(v);   /* [port] */",
          "  }",
          "  /* scrolling down on the landing flows into City Overview */")],

  /* the landing teaser needs a verdict per city; the three new sample cities
     take theirs from this branch's place data (src/data/metros.ts, the
     2017–2022 window the tree reads) */
  ["sub", "city hints for the sample cities",
    '    "Boston, United States of America":  { dir:"up",   rate: 0.3, pay: 5.1, word:"growing slowly", head:"<strong>Boston is growing slowly</strong>" },',
    lines('    "Boston, United States of America":  { dir:"up",   rate: 0.3, pay: 5.1, word:"growing slowly", head:"<strong>Boston is growing slowly</strong>" },',
          '    /* [port] this branch\'s sample cities, from src/data/metros.ts (places, 2017–2022) */',
          '    "Memphis, United States of America":     { dir:"down", rate:-1.0, pay: 4.3, word:"shrinking", head:"<strong>Memphis is shrinking</strong>" },',
          '    "San Antonio, United States of America": { dir:"down", rate:-0.5, pay: 4.4, word:"shrinking", head:"<strong>San Antonio is shrinking</strong>" },',
          '    "San Jose, United States of America":    { dir:"down", rate:-1.1, pay: 7.4, word:"shrinking", head:"<strong>San Jose is shrinking</strong>" },')],

  ["sub", "intro skip button init runs now",
    lines('  document.addEventListener("DOMContentLoaded", ()=>{',
          "    const skipBtn=document.querySelector('.intro-skip');"),
    lines("  (()=>{   /* [port] runs now: the document loaded long ago */",
          "    const skipBtn=document.querySelector('.intro-skip');")],
  ["sub", "intro skip button init closes",
    lines("      skipBtn.classList.toggle('hidden', !isIntroPage);",
          "    }",
          "  });"),
    lines("      skipBtn.classList.toggle('hidden', !isIntroPage);",
          "    }",
          "  })();")],

  /* ---- small screens (Sept 2026; the CSS side is src/legacy/port.css) ---- */

  /* the landing scrolls on narrow screens (its hero stacks and no longer
     fits one viewport), so a wheel or an upward swipe there has to scroll
     it rather than enter the tool — the Diagnose button and the jump links
     do that */
  ["sub", "landing wheel/swipe entry only where the landing does not scroll",
    lines('  landingEl.addEventListener("wheel", e=>{',
          '    if(e.deltaY>8) enterTool("page-overview");',
          "  }, {passive:true});",
          "  let touchY=null;",
          '  landingEl.addEventListener("touchstart", e=>{ touchY=e.touches[0].clientY; }, {passive:true});',
          '  landingEl.addEventListener("touchmove", e=>{',
          '    if(touchY!==null && touchY-e.touches[0].clientY>30){ touchY=null; enterTool("page-overview"); }',
          "  }, {passive:true});"),
    lines('  /* [port] below 920px the landing is a scrolling page (src/legacy/port.css):',
          "     a wheel or a swipe scrolls it, and the buttons enter the tool */",
          '  const landingScrolls=()=>window.matchMedia("(max-width: 920px)").matches;',
          '  landingEl.addEventListener("wheel", e=>{',
          '    if(!landingScrolls() && e.deltaY>8) enterTool("page-overview");',
          "  }, {passive:true});",
          "  let touchY=null;",
          '  landingEl.addEventListener("touchstart", e=>{ touchY=e.touches[0].clientY; }, {passive:true});',
          '  landingEl.addEventListener("touchmove", e=>{',
          "    if(landingScrolls()) return;",
          '    if(touchY!==null && touchY-e.touches[0].clientY>30){ touchY=null; enterTool("page-overview"); }',
          "  }, {passive:true});")],

  /* each tab carries its name twice — the full name and a short one — and
     the stylesheet shows one or the other by width */
  ["sub", "section tabs carry a short name",
    "    b.innerHTML = '<span class=\"num\">' + (i + 1) + \"</span>\" + sd.name;",
    lines("    /* [port] the short name shows below 640px (src/legacy/port.css) */",
          "    const shortName = ({\"Economic Fundamentals\":\"Fundamentals\",\"Metro Industries\":\"Industries\",",
          "      \"Admin Industry Mix\":\"Admin mix\",\"City Constraints\":\"Constraints\",\"Levers for Change\":\"Levers\"})[sd.name] || sd.name;",
          "    b.innerHTML = '<span class=\"num\">' + (i + 1) + '</span><span class=\"secnav-name\">' + sd.name +",
          "      '</span><span class=\"secnav-short\" aria-hidden=\"true\">' + shortName + '</span>';")],

  /* the section bar's city button prints city and country as two spans, so
     a phone can show the city alone */
  ["sub", "city button: city and country apart",
    "      btn.innerHTML = '<span class=\"citypick-txt\">' + sel.value + '</span>';",
    lines("      /* [port] on the bar the two halves are spans, so a phone shows the city alone */",
          "      const cc = bar ? sel.value.split(/,\\s*/) : null;",
          "      btn.innerHTML = cc && cc.length > 1",
          "        ? '<span class=\"citypick-txt\"><span class=\"citypick-city\">' + cc[0] + '</span><span class=\"citypick-ctry\">' + cc.slice(1).join(\", \") + '</span></span>'",
          "        : '<span class=\"citypick-txt\">' + sel.value + '</span>';")],

  /* the tab strip scrolls sideways once it no longer fits: the active tab
     is brought into the middle of the strip on every switch */
  ["sub", "active tab scrolled into view",
    lines('    [...secNavEl.children].forEach((b, k) => {',
          '      b.classList.toggle("is-active", k === i);',
          '      if(k === i) b.setAttribute("aria-current", "page");',
          '      else b.removeAttribute("aria-current");',
          "    });"),
    lines('    [...secNavEl.children].forEach((b, k) => {',
          '      b.classList.toggle("is-active", k === i);',
          '      if(k === i) b.setAttribute("aria-current", "page");',
          '      else b.removeAttribute("aria-current");',
          "    });",
          "    /* [port] the strip scrolls sideways on narrow screens (src/legacy/port.css):",
          "       centre the active tab in it */",
          "    const tab = secNavEl.children[i];",
          "    if(tab && secNavEl.scrollWidth > secNavEl.clientWidth + 1){",
          "      const nr = secNavEl.getBoundingClientRect(), tr = tab.getBoundingClientRect();",
          '      secNavEl.scrollTo({ left: secNavEl.scrollLeft + (tr.left - nr.left) - (nr.width - tr.width) / 2, behavior: "smooth" });',
          "    }")],
];

/* the same, for the second inline script (the section scrollies) */
const PAGE2_PATCHES = [
  /* the two scrolly spies (Metro Industries / Admin Mix, and Economic
     Fundamentals' opt-2) pick the step nearest 45% of the viewport. Below
     920px the stage is pinned ON TOP of the steps (src/legacy/port.css), so
     the reading line is 45% of the band UNDER the stage — otherwise the
     figure changes a screen before its caption arrives. */
  ["suball", "scrolly spies read the band under a stacked stage",
    lines("  function spy(){",
          "    if (!built) return;",
          "    var mid = window.innerHeight * 0.45, best = 0, bd = Infinity;"),
    lines("  function spy(){",
          "    if (!built) return;",
          "    var mid = window.innerHeight * 0.45, best = 0, bd = Infinity;",
          "    /* [port] one-column layout: the stage is pinned above the steps, so the",
          "       reading line is 45% of the band under it, not of the viewport */",
          '    if (window.matchMedia("(max-width: 920px)").matches) {',
          '      var stk = built.steps[0] && built.steps[0].closest(".ct-scrolly");',
          '      var stg = stk && stk.querySelector(".ct-stage");',
          "      if (stg) { var sb = stg.getBoundingClientRect().bottom; mid = sb + (window.innerHeight - sb) * 0.45; }",
          "    }"),
    2],

  /* the population chart sizes to its host but never under 500 units, which
     on a 360px phone draws it 40% too wide; a phone column is ~320 */
  ["sub", "population chart fits a phone column",
    "    var W = Math.max(500, Math.round(avail));",
    "    var W = Math.max(320, Math.round(avail));   /* [port] was 500 */"],
];

function applyPatches(text, patches) {
  for (const p of patches) {
    const [kind, label] = p;
    text = kind === "sub"
      ? subOnce(text, p[2], p[3], `patch "${label}"`)
      : kind === "suball"
        ? subAll(text, p[2], p[3], p[4], `patch "${label}"`)
        : cutBetween(text, p[2], p[3], p[4], `patch "${label}"`);
  }
  return text;
}
const page = applyPatches(script1, PAGE_PATCHES);
const page2 = applyPatches(script2, PAGE2_PATCHES);

const pageModule = lines(
  `/* ${GEN("index.html (the two inline <script> blocks)")}`,
  "   Every departure from the upstream text is marked [port] and comes from",
  "   PAGE_PATCHES in that script. */",
  'import * as d3 from "d3";',
  'import * as L from "leaflet";',
  "",
  "/* [port] both inline scripts, in order, in one function scope: they shared the",
  "   page's global scope on main, and the second reads the first's declarations */",
  "export function initPage(){",
  page,
  "",
  "  /* [port] the React constraints scrolly tracks a sticky stage that no outside",
  "     measure can read, so it reports its own page the way updateActivePage does */",
  "  function markPage(id){",
  "    if(!pageIds.includes(id)) return;",
  "    currentPageId=id; currentStepId=id;",
  "    visitedPages.add(id);",
  "    if(window.__cities) window.__cities.onPage(id);",
  "  }",
  "",
  "  /* ===== [port] cities-v-3's second inline script starts here ===== */",
  page2,
  "",
  "  /* [port] what the markup's inline handlers reach for (the rerouted goTo and",
  "     enterTool, since this runs last), and what the React app drives */",
  "  Object.assign(window, { enterTool, backToLanding, goTo, toggleExplainers, introSlide,",
  "    lockSlider, lockDot, twPick, twBack, twReset, openGeoMap, closeGeoMap, closeJourney,",
  "    journeyGoTo, downloadInsights, sendChat, closeChat, downloadChatCsv,",
  "    submitPracticeOverview, submitPractice, shareViz });",
  "  return { syncCity, goTo, enterTool, backToLanding, toggleExplainers, openJourney, markPage, sectionDefs };",
  "}",
  "",
);
write("src/legacy/v3-page.js", pageModule);

console.log("done");
