#!/usr/bin/env node
/* Port the cities-v-1 prototype (the static site on main) into this app.

   usage:  node scripts/v3/port.mjs --src <directory holding cities-v-1's files>

   e.g.    rm -rf $TMP/v1 && mkdir -p $TMP/v1 && git archive origin/main cities-v-1 | tar -x -C $TMP/v1
           node scripts/v3/port.mjs --src $TMP/v1/cities-v-1

   The source is main's MAIN LINE, cities-v-1/. It was cities-v-3/ until
   2026-09-14, when main re-created v-1 as an exact copy of v-3 and moved the
   layout work there; the "v3" in this script's path and in the generated
   file names dates from then and was kept so nothing had to be rewired.

   Main's page IS the app's shell: its landing, masthead, section tabs and
   pager, journey window, dialogs and every section but Constraints Diagnosis
   come across as they are. React renders only Constraints Diagnosis (and the
   Explainers content) into slots inside that markup. What it writes:

     src/legacy/html/body.html             main's <body>, with the slots and a few swaps (below)
     src/legacy/v3.css                     main's stylesheet, verbatim but for the landing image
     src/legacy/treemap.js                 treemap.js as a module: a function that returns its init()
     src/legacy/xch_geo.js                 the boundary data, verbatim
     src/legacy/v3-page.js                 the two inline scripts, wrapped as one module and patched
     src/legacy/assets/landing-page.webp   the landing image (bundled through an import)
     public/legacy/assets/gl_logo.png      the logo the markup references
     public/legacy/rca-distributions.html  the page the Extras section frames, verbatim

   Every edit to main's text is a step in this file, anchored on a line of the
   upstream text and asserted to match exactly once — so a re-sync that no
   longer fits fails loudly here rather than quietly in the browser. */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const args = process.argv.slice(2);
const srcIdx = args.indexOf("--src");
if (srcIdx < 0 || !args[srcIdx + 1]) {
  console.error("usage: node scripts/v3/port.mjs --src <cities-v-1 dir>");
  process.exit(1);
}
const SRC = path.resolve(args[srcIdx + 1]);

const read = (f) => fs.readFileSync(path.join(SRC, f), "utf8");
const write = (rel, text) => {
  const f = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(f), { recursive: true });
  fs.writeFileSync(f, text);
  console.log(`wrote ${rel} (${text.length.toLocaleString()} chars)`);
};
const copy = (from, rel) => {
  const f = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(f), { recursive: true });
  fs.copyFileSync(path.join(SRC, from), f);
  console.log(`copied ${rel}`);
};
const GEN = (what) =>
  `GENERATED by scripts/v3/port.mjs from cities-v-1/${what} on main. Do not edit by hand:\n` +
  `   re-run the script to re-sync (see src/legacy/README.md).`;

/* ---------- helpers that refuse to guess ---------- */

function indexOnce(text, needle, label) {
  const i = text.indexOf(needle);
  if (i < 0) throw new Error(`${label}: marker not found:\n${needle}`);
  if (text.indexOf(needle, i + 1) >= 0) throw new Error(`${label}: marker is not unique:\n${needle}`);
  return i;
}
/** replace one exact occurrence */
function subOnce(text, from, to, label) {
  const i = indexOnce(text, from, label);
  return text.slice(0, i) + to + text.slice(i + from.length);
}
/** replace every occurrence, insisting there are exactly `n` */
function subAll(text, from, to, n, label) {
  const count = text.split(from).length - 1;
  if (count !== n) throw new Error(`${label}: expected ${n} occurrences, found ${count}`);
  return text.split(from).join(to);
}
/** replace everything from the line that starts with `fromLine` up to (not
 *  including) the line that starts with `toLine` */
function cutBetween(text, fromLine, toLine, replacement, label) {
  const a = indexOnce(text, "\n" + fromLine, `${label} (from)`) + 1;
  const b = indexOnce(text, "\n" + toLine, `${label} (to)`) + 1;
  if (b <= a) throw new Error(`${label}: markers out of order`);
  return text.slice(0, a) + replacement + text.slice(b);
}
const lines = (...ls) => ls.join("\n");

/* ====================================================================
   1 · markup: the whole body, with slots where React draws
   ==================================================================== */

const html = read("index.html");
const LN = html.split("\n");
const lineOf = (needle, from = 0) => {
  const i = LN.findIndex((l, k) => k >= from && l.includes(needle));
  if (i < 0) throw new Error(`markup marker not found: ${needle}`);
  return i;
};

const iBody = lineOf("<body>");
const iScripts = lineOf('<script src="');
const iConstraints = lineOf("<!-- 4 Constraints Diagnosis (empty) -->");
const iLevers = lineOf("<!-- 5 Levers for Change (empty) -->");
const iExplainers = lineOf('<div class="explainers-view" id="explainersView">');
const iExplainersEnd = LN.findIndex((l, k) => k > iExplainers && l === "  </div>");
if (iExplainersEnd < 0) throw new Error("explainers view: closing </div> not found");
if (!(iBody < iConstraints && iConstraints < iLevers && iLevers < iExplainers && iExplainersEnd < iScripts))
  throw new Error("markup markers out of order");

let body = [
  ...LN.slice(iBody + 1, iConstraints),
  /* Constraints Diagnosis is this branch's own section: React renders it
     here. .sec-root marks it as the section's top-level element for the
     switch. */
  '      <!-- 4 Constraints Diagnosis: this branch\'s React section (src/components/ConstraintsSection.tsx) -->',
  '      <div id="constraints-slot" class="sec-root"></div>',
  "",
  ...LN.slice(iLevers, iExplainers),
  /* the Explainers content is React's too (src/components/ExplainersContent.tsx) */
  '  <div class="explainers-view" id="explainersView"></div>',
  ...LN.slice(iExplainersEnd + 1, iScripts),
].join("\n") + "\n";

/* the rail (hidden, but the source of truth for every section's steps) lists
   this branch's constraints steps instead of main's placeholder pages */
body = subOnce(body,
  '<div class="sec" data-sec="page-constraints page-city-in-metro page-constraints-lorem">',
  '<div class="sec" data-sec="page-constraints page-constraints-diagnose page-branch-analysis">',
  "rail: constraints section");
body = subOnce(body,
  lines('          <li data-step="page-constraints"><span class="dot"></span><button onclick="goTo(\'page-constraints\')">How is the metro performing?</button></li>',
        '          <li data-step="page-city-in-metro"><span class="dot"></span><button onclick="goTo(\'page-city-in-metro\')">Is your city pulling with the metro?</button></li>',
        '          <li data-step="page-constraints-lorem"><span class="dot"></span><button onclick="goTo(\'page-constraints-lorem\')">Lorem Ipsum</button></li>'),
  lines('          <li data-step="page-constraints"><span class="dot"></span><button onclick="goTo(\'page-constraints\')">Where is your constraint?</button></li>',
        '          <li data-step="page-constraints-diagnose"><span class="dot"></span><button onclick="goTo(\'page-constraints-diagnose\')">How we diagnose the constraint</button></li>',
        '          <li data-step="page-branch-analysis"><span class="dot"></span><button onclick="goTo(\'page-branch-analysis\')">Branch analysis</button></li>'),
  "rail: constraints steps");

/* the Explainers button comes back to the masthead (main keeps its styles and
   toggleExplainers() looks for #explainersBtn, but dropped it from the markup);
   the book is the one the explainers page header draws */
const BOOK =
  '<svg viewBox="0 0 95.1 79.5" fill="currentColor" aria-hidden="true"><path d="M93,23h-8.4v-5.2c0-1.1-.9-2-2-2-12.1,0-24,2.4-35.2,7-11.2-4.7-23-7-35.2-7-1.1,0-2,.9-2,2v5.2H2c-1.1,0-2,.9-2,2v52.5c0,1.1.9,2,2,2h91.1c1.1,0,2-.9,2-2V25c-.1-1.1-1-2-2.1-2ZM3.9,75.5V26.9h6.5v43.3c0,1.1.9,2,2,2,8,0,15.8,1.2,23.4,3.3H3.9ZM45.5,74.6c-10-3.9-20.5-6.1-31.3-6.3V19.8c10.9.2,21.3,2.4,31.3,6.5v48.3ZM49.5,26.3c10-4.1,20.5-6.3,31.3-6.6v48.6c-10.9.3-21.3,2.4-31.3,6.3V26.3ZM91.1,75.5h-31.9c7.6-2.1,15.4-3.3,23.4-3.3,1.1,0,2-.9,2-2V26.9h6.5v48.6Z"/></svg>';
body = subOnce(body,
  lines('        <div class="spacer"></div>',
        '        <nav class="toolbar-links">'),
  lines('        <div class="spacer"></div>',
        '        <button class="explainers-btn" id="explainersBtn" onclick="toggleExplainers()">' + BOOK + 'Explainers</button>',
        '        <nav class="toolbar-links">'),
  "masthead: explainers button");

/* the city list is this branch's: the four sample cities the diagnostic tree
   has data for (Boston stays the opening one) */
const CITY_OPTIONS = /( *)<option>Boston, United States of America<\/option>\n(?: *<option>[^<\n]*<\/option>\n){4}/g;
const optionMatches = body.match(CITY_OPTIONS);
if (!optionMatches || optionMatches.length !== 2) throw new Error(`city selects: expected 2 option lists, found ${optionMatches?.length ?? 0}`);
body = body.replace(CITY_OPTIONS, (m, indent) => [
  "Memphis, United States of America",
  "San Antonio, United States of America",
  "San Jose, United States of America",
  "Boston, United States of America",
].map((c) => `${indent}<option${c.startsWith("Boston") ? " selected" : ""}>${c}</option>`).join("\n") + "\n");

/* assets and the framed page moved under public/legacy */
body = subAll(body, 'src="assets/gl_logo.png"', 'src="legacy/assets/gl_logo.png"', 2, "logo paths");
body = subOnce(body, 'src="rca-distributions.html?', 'src="legacy/rca-distributions.html?', "extras iframe src");

write("src/legacy/html/body.html", `<!-- ${GEN("index.html <body>")} -->\n` + body);

/* ====================================================================
   2 · stylesheet: verbatim, but the landing image comes through a bundled
       import (src/legacy/index.ts sets --map-asset)
   ==================================================================== */

let css = html.slice(html.indexOf("<style>") + "<style>".length, html.indexOf("</style>"));
css = subAll(css, 'url("assets/landing-page.webp")', "var(--map-asset)", 2, "landing image url");
write("src/legacy/v3.css", `/* ${GEN("index.html <style>")} */\n` + css);

/* ====================================================================
   3 · treemap.js: the IIFE becomes a function that returns its init()
   ==================================================================== */

let tm = read("treemap.js");
const tmOpen = /^\(function\(\)\{\n/m;
if (!tmOpen.test(tm)) throw new Error("treemap.js: opening IIFE not found");
tm = tm.replace(
  tmOpen,
  `/* ${GEN("treemap.js")} */\nimport * as d3 from "d3";\n\n` +
    "/* [port] the IIFE is a function returning its init(), which main ran on\n" +
    "   DOMContentLoaded and src/legacy/index.ts runs once the page is mounted */\n" +
    "export function loadTreemaps(){\n",
);
const tmTail =
  /\n  if \(document\.readyState === "loading"\) \{\n    document\.addEventListener\("DOMContentLoaded", init\);\n  \} else \{\n    init\(\);\n  \}\n\}\)\(\);\n*$/;
if (!tmTail.test(tm)) throw new Error("treemap.js: closing readyState block not found");
tm = tm.replace(tmTail, "\n  return init;\n}\n");
tm = subOnce(tm,
  '"rca-distributions.html?dots=peers&design="',
  '"legacy/rca-distributions.html?dots=peers&design="',
  "treemap.js dist frame url");
write("src/legacy/treemap.js", tm);

write("src/legacy/xch_geo.js", `/* ${GEN("data/geo/xch_geo.js")} */\n` + read("data/geo/xch_geo.js"));
write("public/legacy/rca-distributions.html", read("rca-distributions.html"));
copy("assets/gl_logo.png", "public/legacy/assets/gl_logo.png");
copy("assets/landing-page.webp", "src/legacy/assets/landing-page.webp");

/* ====================================================================
   4 · the page scripts: wrapped as one module, told where React is
   ==================================================================== */

const starts = LN.map((l, i) => (l === "<script>" ? i : -1)).filter((i) => i >= 0);
const ends = LN.map((l, i) => (l === "</script>" ? i : -1)).filter((i) => i >= 0);
if (starts.length !== 2 || ends.length !== 2) throw new Error(`expected two inline scripts, found ${starts.length}`);
const script1 = LN.slice(starts[0] + 1, ends[0]).join("\n");
const script2 = LN.slice(starts[1] + 1, ends[1]).join("\n");

/* [type, label, ...args]: "sub" replaces one exact string; "suball" replaces
   every occurrence, insisting on exactly n of them; "cut" replaces the block
   from one line to the line before another. Applied in order. */
const PAGE_PATCHES = [
  ["sub", "collapsibles run now",
    lines('  window.addEventListener("load", () => {',
          "    setTimeout(initCollapsible, 200);",
          "  });"),
    lines("  /* [port] the page has long loaded by the time this runs: same delay, no event */",
          "  setTimeout(initCollapsible, 200);")],

  /* Constraints Diagnosis is this branch's section: its pages are the anchors
     the React scrolly carries and the branch-analysis page after it */
  ["sub", "pageIds: constraints pages (and Extras, which main left out of its spy)",
    '"page-constraints","page-city-in-metro","page-constraints-lorem","page-levers"];',
    '"page-constraints","page-constraints-diagnose","page-branch-analysis","page-levers","page-extras"];   /* [port] */'],
  ["sub", "sectionDefs: constraints pages",
    '{name:"Constraints Diagnosis",pages:["page-constraints","page-city-in-metro","page-constraints-lorem","check-constraints","apply-constraints"],entry:"page-constraints"},',
    '{name:"Constraints Diagnosis",pages:["page-constraints","page-constraints-diagnose","page-branch-analysis","check-constraints","apply-constraints"],entry:"page-constraints"},   /* [port] */'],

  /* the section switch hides a section by its top-level element; the React
     section's anchors live inside one slot, which is that element */
  ["sub", "section switch: the constraints slot",
    '                   return el && (el.closest(".ov-wrap") || el); })',
    '                   return el && (el.closest(".ov-wrap, .sec-root") || el); })   /* [port] */'],

  /* main's rail highlight looks a rail step up by id, which finds nothing
     once a section is built as a scrolly (the step's own element is
     display:none there) and so falls back to the page; the tab ticks
     already resolve through the scrolly engines — the highlight, which
     feeds the URL hash here, does the same */
  ["sub", "rail highlight resolves scrolly steps",
    "      const el=document.getElementById(li.dataset.step);\n      if(!el) return;\n      const r=el.getBoundingClientRect();\n      if(r.top<=mid && r.bottom>=mid && r.height<bestHeight){",
    "      const el=(window.ovStepFor && window.ovStepFor(li.dataset.step)) ||\n        (window.ctStepFor && window.ctStepFor(li.dataset.step)) || document.getElementById(li.dataset.step);   /* [port] */\n      if(!el) return;\n      const r=el.getBoundingClientRect();\n      if(r.top<=mid && r.bottom>=mid && r.height<bestHeight){"],

  /* the sample journey state names a city the picker no longer offers */
  ["sub", "sample explored cities",
    '  exploredCities.add("Chicago, United States of America");',
    '  exploredCities.add("Memphis, United States of America");   /* [port] */'],

  ["sub", "inview observer guard",
    "  pageIds.forEach(id=>observer.observe(document.getElementById(id)));",
    "  pageIds.forEach(id=>{ const el=document.getElementById(id); if(el) observer.observe(el); });   /* [port] */"],

  /* what React needs to hear: the page in view (for the URL hash), the
     Explainers tab, and the city */
  ["sub", "rail highlight tells React",
    lines("    currentPageId=bestId;",
          "    currentStepId=stepId;",
          "    visitedPages.add(bestId);"),
    lines("    currentPageId=bestId;",
          "    currentStepId=stepId;",
          "    visitedPages.add(bestId);",
          "    if(window.__cities) window.__cities.onPage(stepId);   /* [port] */")],
  ["sub", "explainers toggle tells React",
    lines('    body.style.display=open?"none":"flex";',
          '    btn.classList.toggle("active",open);',
          "  }"),
    lines('    body.style.display=open?"none":"flex";',
          '    if(btn) btn.classList.toggle("active",open);',
          "    if(window.__cities) window.__cities.onExplainers(open);   /* [port] */",
          "  }")],
  ["sub", "city sync tells React",
    lines('    document.querySelectorAll(".city-short").forEach(el=>el.textContent=v.split(",")[0]);',
          "  }",
          "  /* scrolling down on the landing flows into City Overview */"),
    lines('    document.querySelectorAll(".city-short").forEach(el=>el.textContent=v.split(",")[0]);',
          "    if(window.__cities) window.__cities.onCity(v);   /* [port] */",
          "  }",
          "  /* scrolling down on the landing flows into City Overview */")],

  /* the landing teaser needs a verdict per city; the three new sample cities
     take theirs from this branch's place data (src/data/metros.ts, the
     2017–2022 window the tree reads) */
  ["sub", "city hints for the sample cities",
    '    "Boston, United States of America":  { dir:"up",   rate: 0.3, pay: 5.1, word:"growing slowly", head:"<strong>Boston is growing slowly</strong>" },',
    lines('    "Boston, United States of America":  { dir:"up",   rate: 0.3, pay: 5.1, word:"growing slowly", head:"<strong>Boston is growing slowly</strong>" },',
          '    /* [port] this branch\'s sample cities, from src/data/metros.ts (places, 2017–2022) */',
          '    "Memphis, United States of America":     { dir:"down", rate:-1.0, pay: 4.3, word:"shrinking", head:"<strong>Memphis is shrinking</strong>" },',
          '    "San Antonio, United States of America": { dir:"down", rate:-0.5, pay: 4.4, word:"shrinking", head:"<strong>San Antonio is shrinking</strong>" },',
          '    "San Jose, United States of America":    { dir:"down", rate:-1.1, pay: 7.4, word:"shrinking", head:"<strong>San Jose is shrinking</strong>" },')],

  ["sub", "intro skip button init runs now",
    lines('  document.addEventListener("DOMContentLoaded", ()=>{',
          "    const skipBtn=document.querySelector('.intro-skip');"),
    lines("  (()=>{   /* [port] runs now: the document loaded long ago */",
          "    const skipBtn=document.querySelector('.intro-skip');")],
  ["sub", "intro skip button init closes",
    lines("      skipBtn.classList.toggle('hidden', !isIntroPage);",
          "    }",
          "  });"),
    lines("      skipBtn.classList.toggle('hidden', !isIntroPage);",
          "    }",
          "  })();")],

  /* Small screens: until 2026-09-17 this list also carried a layer for
     narrow screens (the landing's wheel/swipe entry, short tab names, the
     city chip in two spans, the active tab centred in its strip, the
     scrolly spies reading under a stacked stage, a phone floor for the
     population chart), with the CSS side in src/legacy/port.css. Main's
     v-1 has since taken all of that on in its own way (breakpoints at
     1199 / 899 / 599, .secnav-lbl, .cp-rest, landingAtEnd(), its own tab
     centring in showSection), so the port carries none of it now — with
     one exception, the section menu on phones, below. */

  /* ---- the section menu on phones (2026-09-17; a candidate for main) ----
     Main keeps its tab strip at every width and lets it scroll on a phone,
     where it has ~165px beside the location chip: only the current tab is
     in view, the rest are cut, and nothing says the strip moves. At main's
     mobile tier (≤599px, src/legacy/port.css) the strip stands down and the
     sections collapse into one control in the chip's family: a button
     naming the section you are on, and a menu of the five in the tabs' own
     state language (a check behind you, the current one on the tint,
     numbers ahead). Built beside the tabs; rendered by showSection. */
  ["sub", "section menu built beside the tabs",
    lines("    b.addEventListener(\"click\", () => showSection(i));",
          "    secNavEl.appendChild(b);",
          "  });"),
    lines("    b.addEventListener(\"click\", () => showSection(i));",
          "    secNavEl.appendChild(b);",
          "  });",
          "  /* [port] on phones the tab strip stands down (src/legacy/port.css) and the",
          "     sections collapse into one control beside the location chip: a button",
          "     naming the section you are on, and a menu of the five in the tabs' own",
          "     state language. showSection renders both. */",
          "  var secMenuWrap = document.createElement(\"div\");",
          "  secMenuWrap.className = \"secmenu\";",
          "  secMenuWrap.innerHTML =",
          "    '<button type=\"button\" class=\"secmenu-btn\" aria-haspopup=\"menu\" aria-expanded=\"false\">' +",
          "    '<span class=\"num\"></span><span class=\"secmenu-lbl\"></span></button>' +",
          "    '<div class=\"secmenu-list\" role=\"menu\" aria-label=\"Sections\" hidden></div>';",
          "  secNavEl.insertAdjacentElement(\"afterend\", secMenuWrap);",
          "  var secMenuBtn = secMenuWrap.querySelector(\".secmenu-btn\");",
          "  var secMenuList = secMenuWrap.querySelector(\".secmenu-list\");",
          "  function closeSecMenu(){ secMenuList.hidden = true; secMenuBtn.setAttribute(\"aria-expanded\", \"false\"); }",
          "  secMenuBtn.addEventListener(\"click\", () => {",
          "    var open = secMenuList.hidden;",
          "    secMenuList.hidden = !open;",
          "    secMenuBtn.setAttribute(\"aria-expanded\", String(open));",
          "  });",
          "  secMenuList.addEventListener(\"click\", e => {",
          "    var b = e.target.closest(\"[data-go]\");",
          "    if(!b) return;",
          "    closeSecMenu();",
          "    showSection(+b.dataset.go);",
          "  });",
          "  document.addEventListener(\"click\", e => { if(!secMenuWrap.contains(e.target)) closeSecMenu(); });",
          "  document.addEventListener(\"keydown\", e => {",
          "    if(e.key === \"Escape\" && !secMenuList.hidden){ closeSecMenu(); secMenuBtn.focus(); }",
          "  });",
          "  function renderSecMenu(i){",
          "    if(!secMenuList) return;",
          "    var CHECK = '<svg viewBox=\"0 0 10 8\" width=\"9\" height=\"7\" aria-hidden=\"true\"><path d=\"M1 4.2 3.7 6.8 9 1.2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/></svg>';",
          "    secMenuBtn.querySelector(\".num\").textContent = String(i + 1);",
          "    secMenuBtn.querySelector(\".secmenu-lbl\").textContent = SECTIONS[i].name;",
          "    secMenuList.innerHTML = SECTIONS.map((sec, k) =>",
          "      /* the extras sit outside the storyline: listed only while the reader",
          "         is there, as on the tabs */",
          "      (sec.name === \"Extras\" && k !== i) ? \"\" :",
          "      '<button type=\"button\" class=\"secmenu-opt' + (k < i ? \" is-done\" : k === i ? \" is-on\" : \"\") +",
          "      '\" role=\"menuitem\" data-go=\"' + k + '\"' + (k === i ? ' aria-current=\"page\"' : \"\") + '>' +",
          "      '<span class=\"num\">' + (k < i ? CHECK : String(k + 1)) + '</span><span>' + sec.name + '</span></button>'",
          "    ).join(\"\");",
          "    closeSecMenu();",
          "  }")],
  ["sub", "section switch renders the menu",
    lines("      if(k === i) b.setAttribute(\"aria-current\", \"page\");",
          "      else b.removeAttribute(\"aria-current\");",
          "    });",
          "    /* below 1200 the chip row is a filmstrip: bring the section you are"),
    lines("      if(k === i) b.setAttribute(\"aria-current\", \"page\");",
          "      else b.removeAttribute(\"aria-current\");",
          "    });",
          "    renderSecMenu(i);   /* [port] the phone's section menu, beside the tabs */",
          "    /* below 1200 the chip row is a filmstrip: bring the section you are")],
];

/* the same, for the second inline script (the section scrollies); empty
   since main's own small-screen layout arrived (see the note above) */
const PAGE2_PATCHES = [];

function applyPatches(text, patches) {
  for (const p of patches) {
    const [kind, label] = p;
    text = kind === "sub"
      ? subOnce(text, p[2], p[3], `patch "${label}"`)
      : kind === "suball"
        ? subAll(text, p[2], p[3], p[4], `patch "${label}"`)
        : cutBetween(text, p[2], p[3], p[4], `patch "${label}"`);
  }
  return text;
}
const page = applyPatches(script1, PAGE_PATCHES);
const page2 = applyPatches(script2, PAGE2_PATCHES);

const pageModule = lines(
  `/* ${GEN("index.html (the two inline <script> blocks)")}`,
  "   Every departure from the upstream text is marked [port] and comes from",
  "   PAGE_PATCHES in that script. */",
  'import * as d3 from "d3";',
  'import * as L from "leaflet";',
  "",
  "/* [port] both inline scripts, in order, in one function scope: they shared the",
  "   page's global scope on main, and the second reads the first's declarations */",
  "export function initPage(){",
  page,
  "",
  "  /* [port] the React constraints scrolly tracks a sticky stage that no outside",
  "     measure can read, so it reports its own page the way updateActivePage does */",
  "  function markPage(id){",
  "    if(!pageIds.includes(id)) return;",
  "    currentPageId=id; currentStepId=id;",
  "    visitedPages.add(id);",
  "    if(window.__cities) window.__cities.onPage(id);",
  "  }",
  "",
  "  /* ===== [port] cities-v-1's second inline script starts here ===== */",
  page2,
  "",
  "  /* [port] what the markup's inline handlers reach for (the rerouted goTo and",
  "     enterTool, since this runs last), and what the React app drives */",
  "  Object.assign(window, { enterTool, backToLanding, goTo, toggleExplainers, introSlide,",
  "    lockSlider, lockDot, twPick, twBack, twReset, openGeoMap, closeGeoMap, closeJourney,",
  "    journeyGoTo, downloadInsights, sendChat, closeChat, downloadChatCsv,",
  "    submitPracticeOverview, submitPractice, shareViz });",
  "  return { syncCity, goTo, enterTool, backToLanding, toggleExplainers, openJourney, markPage, sectionDefs };",
  "}",
  "",
);
write("src/legacy/v3-page.js", pageModule);

console.log("done");
